name: restro_book
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  scroll_to_index: ^2.0.0
  rect_getter: ^1.0.0
  intl: ^0.18.0
  image_picker: ^1.0.4
  shared_preferences: ^2.0.18
  connectivity_plus: ^3.0.3
  package_info_plus: ^3.0.3
  flutter_svg: ^1.1.6
  google_fonts: ^4.0.4
  table_calendar: ^3.0.9
  url_launcher: ^6.2.1
  get: ^4.6.5
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  #this line is added for localization
  flutter_localizations:
    sdk: flutter

  flutter_lints: ^2.0.0
  very_good_analysis: ^5.0.0+1

dependency_overrides:
  http: ^1.1.0

flutter:

  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
